# scripts/metadata.py

CIRCUIT_METADATA = {
    'Bahrain International Circuit': {
    'cat': 'Permanent',
    'stress': 5,               # Very High (Pirelli)
    'abrasion': 5,             # Very High (Pirelli)
    'overtake_diff': 3,        # Easy to overtake (3 DRS zones + heavy braking)
    'corners': 15,
    'length_km': 5.412,
    'laps': 57,
    'drs_zones': 3,
    'speed_cat': 3,            # Medium-High average speed
    'downforce': 3,            # Medium
    'brake_severity': 4,       # High
    'weather_volatility': 1,   # Desert, almost always dry
    'altitude_m': 7,
    'is_street': 0
},
'Miami International Autodrome': {
    'cat': 'Street',
    'stress': 3,
    'abrasion': 3,
    'overtake_diff': 3,
    'corners': 19,
    'length_km': 5.412,
    'laps': 57,
    'drs_zones': 3,
    'speed_cat': 4,
    'downforce': 3,
    'brake_severity': 4,
    'weather_volatility': 4,
    'altitude_m': 7,
    'is_street': 1
},
'Las Vegas Strip Circuit': {
    'cat': 'Street',
    'stress': 2,
    'abrasion': 2,
    'overtake_diff': 2,
    'corners': 17,
    'length_km': 6.201,
    'laps': 50,
    'drs_zones': 2,
    'speed_cat': 5,
    'downforce': 2,
    'brake_severity': 4,
    'weather_volatility': 1,
    'altitude_m': 610,
    'is_street': 1
},
'Jeddah Corniche Circuit': {
    'cat': 'Street',
    'stress': 2,
    'abrasion': 2,
    'overtake_diff': 2,
    'corners': 27,
    'length_km': 6.174,
    'laps': 50,
    'drs_zones': 3,
    'speed_cat': 5,
    'downforce': 2,
    'brake_severity': 3,
    'weather_volatility': 1,
    'altitude_m': 15,
    'is_street': 1
},
'Lusail International Circuit': {
    'cat': 'Permanent',
    'stress': 5,
    'abrasion': 4,
    'overtake_diff': 4,
    'corners': 16,
    'length_km': 5.419,
    'laps': 57,
    'drs_zones': 1,
    'speed_cat': 4,
    'downforce': 4,
    'brake_severity': 3,
    'weather_volatility': 1,
    'altitude_m': 10,
    'is_street': 0
},
'Hanoi Street Circuit': {
    'cat': 'Street',
    'stress': 3,
    'abrasion': 3,
    'overtake_diff': 2,
    'corners': 23,
    'length_km': 5.607,
    'laps': 55,
    'drs_zones': 3,
    'speed_cat': 5,
    'downforce': 3,
    'brake_severity': 4,
    'weather_volatility': 4,
    'altitude_m': 15,
    'is_street': 1
},
'Mugello Circuit': {
    'cat': 'Permanent',
    'stress': 5,
    'abrasion': 5,
    'overtake_diff': 5,
    'corners': 15,
    'length_km': 5.245,
    'laps': 59,
    'drs_zones': 1,
    'speed_cat': 5,
    'downforce': 5,
    'brake_severity': 2,
    'weather_volatility': 3,
    'altitude_m': 292,
    'is_street': 0
},
'Autódromo Internacional do Algarve': {
    'cat': 'Permanent',
    'stress': 3,
    'abrasion': 2,
    'overtake_diff': 3,
    'corners': 15,
    'length_km': 4.653,
    'laps': 66,
    'drs_zones': 1,
    'speed_cat': 4,
    'downforce': 3,
    'brake_severity': 3,
    'weather_volatility': 3,
    'altitude_m': 108,
    'is_street': 0
},
'Istanbul Park': {
    'cat': 'Permanent',
    'stress': 5,
    'abrasion': 2,
    'overtake_diff': 3,
    'corners': 14,
    'length_km': 5.338,
    'laps': 58,
    'drs_zones': 2,
    'speed_cat': 4,
    'downforce': 4,
    'brake_severity': 3,
    'weather_volatility': 4,
    'altitude_m': 99,
    'is_street': 0
},
'Nürburgring GP-Strecke': {
    'cat': 'Permanent',
    'stress': 3,
    'abrasion': 3,
    'overtake_diff': 3,
    'corners': 15,
    'length_km': 5.148,
    'laps': 60,
    'drs_zones': 2,
    'speed_cat': 4,
    'downforce': 3,
    'brake_severity': 4,
    'weather_volatility': 5,
    'altitude_m': 620,
    'is_street': 0
},
'Autodromo Internazionale Enzo e Dino Ferrari': {
    'cat': 'Permanent',
    'stress': 4,
    'abrasion': 3,
    'overtake_diff': 4,
    'corners': 19,
    'length_km': 4.909,
    'laps': 63,
    'drs_zones': 1,
    'speed_cat': 4,
    'downforce': 4,
    'brake_severity': 3,
    'weather_volatility': 3,
    'altitude_m': 38,
    'is_street': 0
},
'Red Bull Ring': {
    'cat': 'Permanent',
    'stress': 3,
    'abrasion': 3,
    'overtake_diff': 2,
    'corners': 10,
    'length_km': 4.318,
    'laps': 71,
    'drs_zones': 3,
    'speed_cat': 5,
    'downforce': 2,
    'brake_severity': 5,
    'weather_volatility': 4,
    'altitude_m': 677,
    'is_street': 0
},
'Albert Park Circuit': {
    'cat': 'Street',
    'stress': 3,
    'abrasion': 2,
    'overtake_diff': 3,
    'corners': 14,
    'length_km': 5.278,
    'laps': 58,
    'drs_zones': 4,
    'speed_cat': 4,
    'downforce': 3,
    'brake_severity': 3,
    'weather_volatility': 4,
    'altitude_m': 20,
    'is_street': 1
},
'Shanghai International Circuit': {
    'cat': 'Permanent',
    'stress': 4,
    'abrasion': 3,
    'overtake_diff': 2,
    'corners': 16,
    'length_km': 5.451,
    'laps': 56,
    'drs_zones': 2,
    'speed_cat': 4,
    'downforce': 4,
    'brake_severity': 4,
    'weather_volatility': 3,
    'altitude_m': 5,
    'is_street': 0
},
'Suzuka Circuit': {
    'cat': 'Permanent',
    'stress': 5,
    'abrasion': 4,
    'overtake_diff': 4,
    'corners': 18,
    'length_km': 5.807,
    'laps': 53,
    'drs_zones': 1,
    'speed_cat': 5,
    'downforce': 5,
    'brake_severity': 3,
    'weather_volatility': 4,
    'altitude_m': 45,
    'is_street': 0
},
'Circuit Gilles Villeneuve': {
    'cat': 'Permanent',
    'stress': 3,
    'abrasion': 2,
    'overtake_diff': 2,
    'corners': 14,
    'length_km': 4.361,
    'laps': 70,
    'drs_zones': 3,
    'speed_cat': 4,
    'downforce': 2,
    'brake_severity': 5,
    'weather_volatility': 4,
    'altitude_m': 13,
    'is_street': 0
},
'Circuit de Monaco': {
    'cat': 'Street',
    'stress': 2,
    'abrasion': 1,
    'overtake_diff': 5,
    'corners': 19,
    'length_km': 3.337,
    'laps': 78,
    'drs_zones': 1,
    'speed_cat': 1,
    'downforce': 5,
    'brake_severity': 2,
    'weather_volatility': 3,
    'altitude_m': 7,
    'is_street': 1
},
'Circuit de Barcelona-Catalunya': {
    'cat': 'Permanent',
    'stress': 4,
    'abrasion': 4,
    'overtake_diff': 3,
    'corners': 14,
    'length_km': 4.657,
    'laps': 66,
    'drs_zones': 2,
    'speed_cat': 4,
    'downforce': 4,
    'brake_severity': 3,
    'weather_volatility': 2,
    'altitude_m': 109,
    'is_street': 0
},
'Silverstone Circuit': {
    'cat': 'Permanent',
    'stress': 5,
    'abrasion': 5,
    'overtake_diff': 2,
    'corners': 18,
    'length_km': 5.891,
    'laps': 52,
    'drs_zones': 2,
    'speed_cat': 5,
    'downforce': 4,
    'brake_severity': 3,
    'weather_volatility': 5,
    'altitude_m': 153,
    'is_street': 0
},
'Spa-Francorchamps': {
    'cat': 'Permanent',
    'stress': 4,
    'abrasion': 3,
    'overtake_diff': 2,
    'corners': 19,
    'length_km': 7.004,
    'laps': 44,
    'drs_zones': 2,
    'speed_cat': 5,
    'downforce': 3,
    'brake_severity': 4,
    'weather_volatility': 5,
    'altitude_m': 470,
    'is_street': 0
},
'Hungaroring': {
    'cat': 'Permanent',
    'stress': 3,
    'abrasion': 3,
    'overtake_diff': 5,
    'corners': 14,
    'length_km': 4.381,
    'laps': 70,
    'drs_zones': 2,
    'speed_cat': 2,
    'downforce': 5,
    'brake_severity': 2,
    'weather_volatility': 3,
    'altitude_m': 264,
    'is_street': 0
},
'Circuit Zandvoort': {
    'cat': 'Permanent',
    'stress': 4,
    'abrasion': 3,
    'overtake_diff': 4,
    'corners': 14,
    'length_km': 4.259,
    'laps': 72,
    'drs_zones': 2,
    'speed_cat': 3,
    'downforce': 4,
    'brake_severity': 2,
    'weather_volatility': 4,
    'altitude_m': 6,
    'is_street': 0
},
'Autodromo Nazionale Monza': {
    'cat': 'Permanent',
    'stress': 3,
    'abrasion': 3,
    'overtake_diff': 2,
    'corners': 11,
    'length_km': 5.793,
    'laps': 53,
    'drs_zones': 2,
    'speed_cat': 5,
    'downforce': 1,
    'brake_severity': 5,
    'weather_volatility': 3,
    'altitude_m': 162,
    'is_street': 0
},
'Madring': {
    'cat': 'Street',
    'stress': 3,
    'abrasion': 3,
    'overtake_diff': 3,
    'corners': 22,
    'length_km': 5.474,
    'laps': 57,
    'drs_zones': 2,
    'speed_cat': 4,
    'downforce': 3,
    'brake_severity': 4,
    'weather_volatility': 2,
    'altitude_m': 667,
    'is_street': 1
},
'Baku City Circuit': {
    'cat': 'Street',
    'stress': 2,
    'abrasion': 2,
    'overtake_diff': 2,
    'corners': 20,
    'length_km': 6.003,
    'laps': 51,
    'drs_zones': 2,
    'speed_cat': 5,
    'downforce': 2,
    'brake_severity': 5,
    'weather_volatility': 2,
    'altitude_m': -28,
    'is_street': 1
},
'Marina Bay Street Circuit': {
    'cat': 'Street',
    'stress': 4,
    'abrasion': 2,
    'overtake_diff': 4,
    'corners': 19,
    'length_km': 4.940,
    'laps': 62,
    'drs_zones': 3,
    'speed_cat': 2,
    'downforce': 5,
    'brake_severity': 4,
    'weather_volatility': 5,
    'altitude_m': 15,
    'is_street': 1
},
'Circuit of the Americas': {
    'cat': 'Permanent',
    'stress': 4,
    'abrasion': 3,
    'overtake_diff': 2,
    'corners': 20,
    'length_km': 5.513,
    'laps': 56,
    'drs_zones': 2,
    'speed_cat': 4,
    'downforce': 3,
    'brake_severity': 4,
    'weather_volatility': 3,
    'altitude_m': 230,
    'is_street': 0
},
'Autódromo Hermanos Rodríguez': {
    'cat': 'Permanent',
    'stress': 3,
    'abrasion': 2,
    'overtake_diff': 2,
    'corners': 17,
    'length_km': 4.304,
    'laps': 71,
    'drs_zones': 3,
    'speed_cat': 5,
    'downforce': 5,
    'brake_severity': 4,
    'weather_volatility': 2,
    'altitude_m': 2240,
    'is_street': 0
},
'Autódromo José Carlos Pace': {
    'cat': 'Permanent',
    'stress': 3,
    'abrasion': 3,
    'overtake_diff': 2,
    'corners': 15,
    'length_km': 4.309,
    'laps': 71,
    'drs_zones': 2,
    'speed_cat': 4,
    'downforce': 3,
    'brake_severity': 3,
    'weather_volatility': 5,
    'altitude_m': 785,
    'is_street': 0
},
'Yas Marina Circuit': {
    'cat': 'Permanent',
    'stress': 3,
    'abrasion': 2,
    'overtake_diff': 3,
    'corners': 16,
    'length_km': 5.281,
    'laps': 58,
    'drs_zones': 2,
    'speed_cat': 3,
    'downforce': 3,
    'brake_severity': 3,
    'weather_volatility': 1,
    'altitude_m': 3,
    'is_street': 0
},
'Hockenheimring': {
    'cat': 'Permanent',
    'stress': 3,
    'abrasion': 3,
    'overtake_diff': 2,
    'corners': 17,
    'length_km': 4.574,
    'laps': 67,
    'drs_zones': 2,
    'speed_cat': 4,
    'downforce': 3,
    'brake_severity': 4,
    'weather_volatility': 4,
    'altitude_m': 103,
    'is_street': 0
},
'Circuit Paul Ricard': {
    'cat': 'Permanent',
    'stress': 3,
    'abrasion': 3,
    'overtake_diff': 2,
    'corners': 15,
    'length_km': 5.842,
    'laps': 53,
    'drs_zones': 2,
    'speed_cat': 4,
    'downforce': 3,
    'brake_severity': 4,
    'weather_volatility': 2,
    'altitude_m': 430,
    'is_street': 0
},
'Sochi Autodrom': {
    'cat': 'Street',
    'stress': 2,
    'abrasion': 2,
    'overtake_diff': 3,
    'corners': 18,
    'length_km': 5.848,
    'laps': 53,
    'drs_zones': 2,
    'speed_cat': 4,
    'downforce': 3,
    'brake_severity': 3,
    'weather_volatility': 3,
    'altitude_m': 25,
    'is_street': 1
}

}

DEFAULT_METADATA = {
    'cat': 'Permanent', 'stress': 3, 'abrasion': 3, 'overtake_diff': 5, 
    'corners': 15, 'length_km': 5.0, 'laps': 55, 'drs_zones': 2, 
    'speed_cat': 3, 'downforce': 3, 'brake_severity': 3, 
    'weather_volatility': 3, 'altitude_m': 100, 'is_street': 0
}

import unicodedata
import re

def normalize_circuit_name(name):
    if not isinstance(name, str):
        return ""
    # Strip accents
    name = unicodedata.normalize('NFD', name).encode('ascii', 'ignore').decode('utf-8')
    # Lowercase and keep alphanumeric only
    return re.sub(r'[^a-z0-9]', '', name.lower())

NORMALIZED_CIRCUIT_METADATA = {normalize_circuit_name(k): v for k, v in CIRCUIT_METADATA.items()}

def get_circuit_metadata(circuit_name):
    norm_name = normalize_circuit_name(circuit_name)
    if norm_name in NORMALIZED_CIRCUIT_METADATA:
        return NORMALIZED_CIRCUIT_METADATA[norm_name]
    
    # Keyword/alias matching
    aliases = {
        'enzo': 'Autodromo Internazionale Enzo e Dino Ferrari',
        'imola': 'Autodromo Internazionale Enzo e Dino Ferrari',
        'interlagos': 'Autódromo José Carlos Pace',
        'pace': 'Autódromo José Carlos Pace',
        'saopaulo': 'Autódromo José Carlos Pace',
        'portimao': 'Autódromo Internacional do Algarve',
        'algarve': 'Autódromo Internacional do Algarve',
        'qatar': 'Lusail International Circuit',
        'aldaayen': 'Lusail International Circuit',
        'gilles': 'Circuit Gilles Villeneuve',
        'montreal': 'Circuit Gilles Villeneuve',
        'americas': 'Circuit of the Americas',
        'cota': 'Circuit of the Americas',
        'austin': 'Circuit of the Americas',
        'hermanos': 'Autódromo Hermanos Rodríguez',
        'rodriguez': 'Autódromo Hermanos Rodríguez',
        'monza': 'Autodromo Nazionale Monza',
        'monaco': 'Circuit de Monaco',
        'montecarlo': 'Circuit de Monaco',
        'catalunya': 'Circuit de Barcelona-Catalunya',
        'barcelona': 'Circuit de Barcelona-Catalunya',
        'montmelo': 'Circuit de Barcelona-Catalunya',
        'spa': 'Spa-Francorchamps',
        'zandvoort': 'Circuit Zandvoort',
        'baku': 'Baku City Circuit',
        'singapore': 'Marina Bay Street Circuit',
        'marinabay': 'Marina Bay Street Circuit',
        'yas': 'Yas Marina Circuit',
        'abudhabi': 'Yas Marina Circuit',
        'silverstone': 'Silverstone Circuit',
        'hockenheim': 'Hockenheimring',
        'paulricard': 'Circuit Paul Ricard',
        'lecastellet': 'Circuit Paul Ricard',
        'sochi': 'Sochi Autodrom',
        'vegas': 'Las Vegas Strip Circuit',
        'jeddah': 'Jeddah Corniche Circuit',
        'miami': 'Miami International Autodrome',
        'bahrain': 'Bahrain International Circuit',
        'sakhir': 'Bahrain International Circuit',
        'albert': 'Albert Park Circuit',
        'melbourne': 'Albert Park Circuit',
        'suzuka': 'Suzuka Circuit',
        'shanghai': 'Shanghai International Circuit',
        'lusail': 'Lusail International Circuit',
        'hungaroring': 'Hungaroring',
        'mugello': 'Mugello Circuit',
        'istanbul': 'Istanbul Park',
        'nurburgring': 'Nürburgring GP-Strecke',
        'nurburg': 'Nürburgring GP-Strecke',
        'hanoi': 'Hanoi Street Circuit',
        'spielberg': 'Red Bull Ring'
    }
    for keyword, key in aliases.items():
        if keyword in norm_name:
            return CIRCUIT_METADATA[key]
            
    return DEFAULT_METADATA